name: CI/CD Application

on:
  push:
    branches:
      - lab9
      - main
  pull_request:
    branches:
      - lab9
      - main
  workflow_dispatch:
    inputs:
      build:
        description: 'Build the project'
        required: true
        default: 'true'
      upload:
        description: 'Upload the artifact'
        required: true
        default: 'true'
      analyze:
        description: 'Run static analysis'
        required: true
        default: 'true'

jobs:
  push_job:
    name: Build and Upload
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
      - name: before_script
        run: |
          corepack enable
          corepack prepare pnpm@latest-10 --activate
          pnpm config set store-dir .pnpm-store
      - name: Install dependencies
        run: pnpm install
      - name: Build project
        run: pnpm build

      - name: Upload artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: vue2048-build
          path: dist/

  pull_request_job:
    name: Pull Request Checks
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
      - name: before_script
        run: |
          corepack enable
          corepack prepare pnpm@latest-10 --activate
          pnpm config set store-dir .pnpm-store
      - name: Install dependencies
        run: pnpm install
      - name: Build project
        run: pnpm build

      - name: Run type checking
        run: pnpm type-check
      - name: Run linter
        run: pnpm lint
      - name: Run quality
        run: pnpm test